### ISSUE TITLE
Battle class

### ISSUE THREAD

**Issue by nickcontino** [joshuaohana/StarTrekDeck#3]
hey man - 

trying to make some battle functionality, instantiating a class 'Battle' with two instances of Player as parameters. 

in class Hand I have function calcstats (line 18 of Hand) which we worked on before. I have it returning cardstats (line 30 of Hand), which is a dictionary that has the values I need to begin making class Battle work. But I just can't seem to figure out how to make local variable cardstats, once it's been worked on by calcstats, more global. I realize that any variable defined within a function can only be accessed from within that function. I want to jettison out cardstats to use elsewhere. Maybe I'm not entirely clear on how return works. 

your zenmaster advice would be appreciated

nick

**Comment by joshuaohana** [comment]
all righty then, okay

1) Accessing cardstats: Card stats is a member (happens to be a function instead of a variable) of class Hand. So, when you want it, you just do handName.cardstats() and it'll return the object. You did that once in battle correctly on line 12, cool beans. It's really that simple. Any time you want to access cardstats of a hand and you have a reference to the hand you want the calcstatus of, you just do handname.cardstats()

2) Return: Return "returns" something back from the function, the caller of the function decides what to do with it. ex:

function foo ()
  return "foo"

print foo()

the above code will call the function foo, foo returns "foo", then your line print foo() will print the returned value from foo()

3) Don't use exclamation marks in file names

4) Your battle class, do your thing... but I would recommend it not be a class. Think of it this way. A class is a Thing that you create instances of, which you then use and re-use. If it were me, I would create a battle function as a static\* function within class Hand (since essentially a battle is between two hands right), then you could do some mathing at them and return the winner! Example below

@staticmethod
def battle(player1, player2):
  player1stats = player1.hand.calcstats()
  player2stats = player2.hand.calcstatus()
  # do some math here
  # return your winner, maybe adjust the player's health? whatever else
...
Hand.battle(hand1, hand2)

note the lack of self, that's because it's static, there's no reference to "myself", you just directly access player1 and player2

**Comment by nickcontino** [comment]
Sweet man. I'll integrate these changes. You're right, battle doesn't need to be a class. Static methods are still a bit mysterious to me so I'll do some research on them.

**Comment by joshuaohana** [comment]
A class method is one that belongs to the class. 
Assume you have the following class and methods as an example

```
class Foo
   @staticmethod
    def astaticmethod():
         blah blah blah
    def aregularmethod(self):
         blah blah blah
```

and an instantiation of it
`myFoo = Foo()`

If it is not static (aka: regular) it:
1. has a reference to self
2. is called by an instantiation of the object, eg: myFoo.aregularmethod()
3. cannot be called generically against the class, eg: Foo.aregularmethod() will cause an error

If it is static it:
1. has a reference to self
2. is called by any reference to the class, eg: Foo.astaticmethod()

**Comment by nickcontino** [comment]
that's definitely the best explanation I've seen of class methods vs class
methods. thanks man. as I write more, I will internalize these concepts. I
did some battle system stuff, and I'm pretty sure it works. I'll push it in
a little bit once I've put the _finishing touches_ on

Nick Contino
941-448-8999

"Do or do not, there is no try"
-Yoda
